version: '3.3'
services:
  postgres_pedidos:
    image: postgres:15
    container_name: postgres_gestao_pedidos
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pedidodb
    ports:
      - 5450:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data